source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "rack-cors"
gem "puma"
gem "bootsnap", require: false
gem "http"
gem "stripe", "~> 10.0"
gem "front_matter_parser", "~> 1.0"
gem "redcarpet", "~> 3.6"

gem "redis", "~> 5.4"
